#!/usr/bin/env python3
"""Walk kb/**/*.md, parse frontmatter, rewrite INDEX*.md, validate links.

Usage:
    python update_index.py --kb <path-to-kb>

Exit code 0 on success even if some cards have bad YAML (those are skipped
and warned about); non-zero only on unrecoverable I/O errors.
"""
from __future__ import annotations

import argparse
import datetime as dt
import pathlib
import sys
from collections import defaultdict
from dataclasses import dataclass

import yaml


@dataclass
class Card:
    path: pathlib.Path
    id: str
    title: str
    source: str
    primary_tag: str
    tags: list[str]
    created: str
    confidence: str
    status: str
    links: list[dict]  # each link: {"id": str, "rel": str}


def normalize_link(raw: object) -> dict | None:
    """Convert a frontmatter link entry into the uniform {id, rel} dict.

    Accepts the legacy list-of-str form (id only, defaults rel='see-also')
    and the new list-of-dict form. Returns None for malformed entries.
    """
    if isinstance(raw, str):
        return {"id": raw, "rel": "see-also"}
    if isinstance(raw, dict) and "id" in raw:
        return {"id": str(raw["id"]), "rel": str(raw.get("rel", "see-also"))}
    return None


def parse_card(path: pathlib.Path) -> Card | None:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        print(f"WARN: cannot read {path}: {e}", file=sys.stderr)
        return None
    if not text.startswith("---\n"):
        print(f"WARN: missing frontmatter in {path}", file=sys.stderr)
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        print(f"WARN: malformed frontmatter in {path}", file=sys.stderr)
        return None
    try:
        fm = yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError as e:
        print(f"WARN: bad YAML in {path}: {e}", file=sys.stderr)
        return None
    required = ("id", "title", "primary_tag", "created")
    if not all(k in fm for k in required):
        print(f"WARN: missing required keys in {path}", file=sys.stderr)
        return None
    raw_links = fm.get("links") or []
    norm_links = [normalize_link(l) for l in raw_links]
    links = [l for l in norm_links if l is not None]
    return Card(
        path=path,
        id=str(fm["id"]),
        title=str(fm["title"]),
        source=str(fm.get("source", "unknown")),
        primary_tag=str(fm["primary_tag"]),
        tags=list(fm.get("tags") or []),
        created=str(fm["created"]),
        confidence=str(fm.get("confidence", "medium")),
        status=str(fm.get("status", "draft")),
        links=links,
    )


def collect_cards(kb: pathlib.Path) -> list[Card]:
    cards: list[Card] = []
    for md in sorted(kb.glob("*/*.md")):
        if md.parent == kb:
            continue
        if md.parent.name.startswith(".") or md.parent.name == "_render":
            continue
        # Per-tag README.md is a navigation primer, not a card.
        if md.name == "README.md":
            continue
        card = parse_card(md)
        if card is not None:
            cards.append(card)
    return cards


def find_broken_links(cards: list[Card]) -> list[tuple[Card, str]]:
    ids = {c.id for c in cards}
    broken: list[tuple[Card, str]] = []
    for c in cards:
        for link in c.links:
            link_id = link["id"]
            if link_id not in ids:
                broken.append((c, link_id))
    return broken


def rel(card: Card, kb: pathlib.Path) -> str:
    return card.path.relative_to(kb).as_posix()


def first_nonempty_body_line(card: Card) -> str:
    text = card.path.read_text(encoding="utf-8")
    body = text.split("---", 2)[2] if text.count("---") >= 2 else text
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("<") and line.endswith(">"):
            continue
        return line[:120]
    return ""


def write_index_md(kb: pathlib.Path, cards: list[Card], broken: list[tuple[Card, str]]) -> None:
    by_tag: dict[str, int] = defaultdict(int)
    for c in cards:
        by_tag[c.primary_tag] += 1
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "<!-- AUTO-GENERATED by update_index.py — DO NOT EDIT -->",
        f"<!-- Last updated: {now} | {len(cards)} cards | {len(broken)} broken links -->",
        "",
        "# Knowledge Base Index",
        "",
        "Source-of-truth: markdown files under `kb/<tag>/`.",
        "",
        "## Tag overview",
    ]
    if not by_tag:
        lines.append("(no cards yet)")
    else:
        for tag in sorted(by_tag):
            lines.append(f"- [{tag}]({tag}/README.md) ({by_tag[tag]} cards)")
    lines += [
        "",
        "## Detailed indexes",
        "- [By tag](INDEX-by-tag.md)",
        "- [By date](INDEX-by-date.md)",
        "",
        "## Health",
        f"- Broken links: {len(broken)}",
    ]
    for card, link in broken:
        lines.append(f"  - ⚠ broken: `{link}` referenced by [{card.id}]({rel(card, kb)})")
    (kb / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_index_by_tag(kb: pathlib.Path, cards: list[Card]) -> None:
    by_tag: dict[str, list[Card]] = defaultdict(list)
    for c in cards:
        by_tag[c.primary_tag].append(c)
    lines = [
        "<!-- AUTO-GENERATED by update_index.py — DO NOT EDIT -->",
        "",
        "# By tag",
        "",
    ]
    for tag in sorted(by_tag):
        lst = sorted(by_tag[tag], key=lambda c: c.created, reverse=True)
        lines.append(f"## {tag} ({len(lst)})")
        for c in lst:
            tldr = first_nonempty_body_line(c)
            lines.append(f"- [{c.id}]({rel(c, kb)}) — {c.title} [{c.source}, conf:{c.confidence}]")
            if tldr:
                lines.append(f"  - _{tldr}_")
        lines.append("")
    (kb / "INDEX-by-tag.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_index_by_date(kb: pathlib.Path, cards: list[Card]) -> None:
    sorted_cards = sorted(cards, key=lambda c: (c.created, c.id), reverse=True)
    lines = [
        "<!-- AUTO-GENERATED by update_index.py — DO NOT EDIT -->",
        "",
        "# By date (most recent first)",
        "",
    ]
    for c in sorted_cards:
        lines.append(f"- {c.created} — [{c.id}]({rel(c, kb)}) — {c.title} [{c.source}, conf:{c.confidence}]")
    (kb / "INDEX-by-date.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kb", required=True, type=pathlib.Path)
    args = parser.parse_args()
    kb: pathlib.Path = args.kb
    if not kb.exists():
        print(f"ERROR: kb dir does not exist: {kb}", file=sys.stderr)
        return 2
    cards = collect_cards(kb)
    broken = find_broken_links(cards)
    write_index_md(kb, cards, broken)
    write_index_by_tag(kb, cards)
    write_index_by_date(kb, cards)
    print(f"Wrote indexes: {len(cards)} cards, {len(broken)} broken links")
    return 0


if __name__ == "__main__":
    sys.exit(main())
